FROM mcr.microsoft.com/mssql/server:2019-latest
EXPOSE 1433:1433
ENV ACCEPT_EULA=true
ENV MSSQL_SA_PASSWORD=Senha123@

RODA ESSE KRL QUE FUNCIONA: docker run -e ACCEPT_EULA=true -e MSSQL_SA_PASSWORD=Senha123@ -p 1433:1433 -d --name sqlserver mcr.microsoft.com/mssql/server:2019-latest